import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Analytics} from '@vercel/analytics/react'
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import BringToTop from "@/components/BringToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background text-foreground relative">
        <Navbar />
        {children}
        <Analytics />
        <BringToTop />
      </body>
    </html>
  )
}
